version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: furniture_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: furniture_store
    volumes:
      - ./mysql_data:/var/lib/mysql

  apache:
    build:
      context: ./docker/apache
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mongo:
    image: mongo
    container_name: furniture_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: furniture_mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo

volumes:
  mysql_data:
  mongo_data:
